# El grupo de datos

M.C. Diana Oaxaca y Dra. Mirna Vazquez Rosas Landa 

02 de agosto de 2022

### Datos

Los datos con los que trabajaremos se enlistan en la siguiente tabla. 

| samples   | BioProject                                                   | Article                                                      |
| --------- | ------------------------------------------------------------ | ------------------------------------------------------------ |
| htn       | [PRJEB13870](https://www.ebi.ac.uk/ena/browser/view/PRJEB13870?show=reads) | **[Gut microbiota dysbiosis contributes to ...](https://link.springer.com/article/10.1186/s40168-016-0222-x#Ack1)** |
| biogas    | [PRJEB21678](https://www.ebi.ac.uk/ena/browser/view/PRJEB21678) | [**Genetic repertoires of anaerobic microbiomes ...**](https://biotechnologyforbiofuels.biomedcentral.com/articles/10.1186/s13068-018-1258-x). |
| pulque    | [PRJNA603591](https://www.ebi.ac.uk/ena/browser/view/PRJNA603591) | [**Genomic profiling of bacterial and fungal ...**](https://www.nature.com/articles/s41598-020-71864-4) |
| sedimento | [PRJNA364776](https://www.ebi.ac.uk/ena/browser/view/PRJNA364776) | [**Microbial Dark Matter project phase II**](https://www.osti.gov/award-doi-service/biblio/10.46936/10.25585/60000876) * |
| tea       | [PRJNA698063](https://www.ebi.ac.uk/ena/browser/view/PRJNA698063) | [**Niche differentiation of microbes......**)](https://www.researchsquare.com/article/rs-347764/v1) |

#### htn
**Sinopsis**: Se realizó secuenciación metagenómica de heces de pacientes sanos (**control**), con pre-hipertensión (**pHTN**) y con hipertensión (**HTN**). Los pacientes con enfermedad presentaron niveles de diversidad drásticamente más bajos en comparación con el grupo control. También hicieron trasplantes fecales de pacientes enfermos a ratones axénicos, el efecto del trasplante demostró que la hipertensión observada en los ratones era derivada de la microbiota trasplantada.

Los datos crudos: PRJEB13870
https://www.ebi.ac.uk/ena/browser/view/PRJEB13870?show=reads

El artículo: Gut microbiota dysbiosis contributes to the development of hypertension sobre microbioma e hipertensión
https://link.springer.com/article/10.1186/s40168-016-0222-x#Ack1

Li, J., Zhao, F., Wang, Y. et al. Gut microbiota dysbiosis contributes to the development of hypertension. Microbiome 5, 14 (2017). https://doi.org/10.1186/s40168-016-0222-x

#### pulque. 

**Sinopsis**: En este trabajo se secuenciaron librerias de Illumina MiSeq de muestras a diferentes tiempos de fermentación: 0 hrs (aguamiel), 3, 6 y 12 horas. En general observaron que la abundancia de los géneros cambió durante la fermentación y se asoció con una disminución de sacarosa, aumento de etanol y ácido láctico (Medidos por HPLC). Predijeron, entre otros, la biosíntesis de folato y vitamina B. Uno de los MAG obtenidos correspondió a Saccharomyces cereviseae relacionado filogenéticamente con S. cerevisiae aislado de sake y bioetanol y otro correspondió a Zymomonas mobilis que propusieron como un nuevo linaje.

Los datos crudos: PRJNA603591
https://www.ebi.ac.uk/ena/browser/view/PRJNA603591

El articulo: Genomic profiling of bacterial and fungal communities and their predictive functionality during pulque fermentation by whole-genome shotgun sequencing
https://www.nature.com/articles/s41598-020-71864-4

Chacón-Vargas, K., Torres, J., Giles-Gómez, M. et al. Genomic profiling of bacterial and fungal communities and their predictive functionality during pulque fermentation by whole-genome shotgun sequencing. Sci Rep 10, 15115 (2020). https://doi.org/10.1038/s41598-020-71864-4

#### sedimento
Microbioma de sedimento del Microbial Dark Matter project (MDMP)

**Sinopsis**: El MDMP es realizado por el Departamento de Energía del JGI, se enfoca en resolver nuevos superphyla de bacterias y arqueas, en la fase uno se secuenciaron 201 linajes enriquecidos no cultivados, mediante single cell sequencing. En esta segunda fase se utilizaron datos públicos de diferentes muestras y regiones del mundo. Aún se siguen procesando datos y hasta el momento han encontrado prometedores SAGs incluído un phylum novedoso en Deward Creek.

Los datos: PRJNA364776
https://www.ebi.ac.uk/ena/browser/view/PRJNA364776

El proyecto: Microbial Dark Matter project phaseII https://www.osti.gov/award-doi-service/biblio/10.46936/10.25585/60000876  


Hedlund, Brian ORCID [1] Woyke, Tanja ORCID [2] Pester, Michael ORCID [3] Spear, John ORCID [4] Hallam, Steven ORCID [5] Eisen, Jonathan [6] Elshahed, Mostafa ORCID [7] Becraft, Eric [8] Dunfield, Peter [9] Teske, Andreas [10] van Heerden, et al. Joint Genome Institute Award.

#### tea
Microbioma de Camellia sinensis (la planta del té verde y negro)

**Sinopsis**: En este trabajo se secuenciaron librerias de Illumina de muestras rizosféricas y endofíticas de _C. sinensis_, el estudio hace una descripción general de la taxonomía y predicción funcional del microbioma, hace énfasis en las diferencias encontradas en la parte endofítica y rizosféricas. 

Los datos: PRJNA698063
https://www.ebi.ac.uk/ena/browser/view/PRJNA698063

El artículo: Niche differentiation of microbes and their functional signatures in Assam type tea (Camellia sinensis var. assamica)
https://www.researchsquare.com/article/rs-347764/v1

Bora, S. S., Dey, K. K., Borah, M., Rahman, M., Gogoi, M., Modi, M. K., & Barooah, M. (2021). Niche differentiation of microbes and their functional signatures in Assam type tea (Camellia sinensis var. assamica).
