---
title: "Workshop CDSB 2022: Análisis avanzado de metagenomas. Creando tus flujos de análisis con R/Bioconductor."
author: "Mirna Vázquez Rosas-Landa, Yalbi Balderas-Martínez, Joselyn Chávez, Erick Cuevas-Fernández, Alejandra Medina-Rivera"
site: bookdown::bookdown_site
documentclass: book
url: 'https://comunidadbioinfo.github.io/cdsb2022/'
github-repo: "comunidadbioinfo/cdsb2022"
output:
  bookdown::gitbook: default
  
---

# Bienvenida {-}

[
```{r, echo=FALSE}
knitr::include_url("https://comunidadbioinfo.github.io/cdsb2021_workflows/bienvenida.html",
  height = "380px")
```
](https://comunidadbioinfo.github.io/cdsb2021_workflows/bienvenida.html)


Les damos la bienvenida al Workshop Análisis avanzado de metagenomas. Creando tus flujos de análisis con R/Bioconductor! 

<p align="justify">
En los últimos años la metagenómica ha cobrado una gran importancia para  el descubrimiento de nuevos grupos microorganismos y rutas metabólicas. En este taller revisaremos los métodos más recientes para analizar datos metagenómicos, usando herramientas de software libre y paquetes de R especializados que están disponibles libremente vía Bioconductor. 

Durante este taller aprenderás a reconstruir genomas a partir de metagenomas utilizando diferentes herramientas de software libre. Revisaremos diferentes estrategias de binning y de predicción metabólica, identificamos áreas de oportunidad para el desarrollo de software en metagenómica, aprenderás también cómo documentar tu código utilizando RMarkdown.


## Instructores

- [Dra. Mirna Vázquez Rosas Landa](https://comunidadbioinfo.github.io/es/authors/mirnavrl/): Estancia Postdoctoral en la Universidad de Texas en Austin.
- [Dra. Joselyn Chávez Fuentes](https://comunidadbioinfo.github.io/es/authors/josschavezf/): Estancia Postdoctoral en Icahn School of Medicine at Mount Sinai.
- [M.C. Erick Cuevas Fernández](https://comunidadbioinfo.github.io/es/authors/erickcufe/): Estudiante de Doctorado en la Universidad Nacional Autónoma de México.
- [Dra. Alejandra Medina Rivera](https://comunidadbioinfo.github.io/es/authors/amedina/): Investigadora Asociada en el Laboratorio Internacional de Investigación de Medicina Genómica, UNAM. 
- [Dra. Yalbi Balderas Martínez](https://comunidadbioinfo.github.io/es/authors/yalbibalderas/):  Investigadora en el Instituto Nacional de Enfermedades Respiratorias Ismael Cosío Villegas.


## Ponentes invitados

- Dr. Brett Baker
- Valerie de Anda 


## Temario 

Consulta el calendario de este curso en: <https://bit.ly/calendarcdsb2022>

### Lunes 01 de agosto

| Horario     | Tema                                       | Instructor             |
|-------------|--------------------------------------------|------------------------|
| 10:00-11:00 | Presentación de la CDSB.                   | Erick Cuevas Fernández |
| 11:00-12:00 | Plática: La última versión del árbol de la vida y la metagenómica. | Dr. Brett Baker |
| 12:00-14:00 | Control de versiones con GitHub y RStudio. | Alejandra Medina       |
| 15:00-17:00 | Generación de Reportes con R markdown.     | Joselyn Chávez         |

### Martes 02 de agosto

| Horario     | Tema                                              | Instructor                        |
|-------------|---------------------------------------------------|-----------------------------------|
| 9:00-10:00  | Plática: Convirtiendo tu flujo de análisis en un paquete de R/Bioconductor. | Por definir |
| 10:00-11:00 | Plática: Paquetes de bioconductor relacionados con la metagenómica. | Mirna Vázquez   |
| 11:30-14:00 | Reconstrucción de genomas. Parte I                | Yalbi Balderas                    |
| 15:00-17:00 | Reconstrucción de genomas. Parte II               | Yalbi Balderas                    |

### Miércoles 03 de agosto

| Horario     | Tema                                                | Instructor              |
|-------------|-----------------------------------------------------|-------------------------|
| 9:00-13:00  | Asignación taxonómica.                              | Mirna Vázquez           |
| 15:00-16:00 | Análisis de vías metabólicas.                       | Mirna Vázquez           |
| 16:00-17:00 | MEBs                                                | Mirna Vázquez           |

### Jueves 04 de agosto

| Horario     | Tema                            | Instructor                                                  |
|-------------|---------------------------------|-------------------------------------------------------------|
| 9:00-14:00  | Proyecto colaborativo. Parte I  | Mirna Vázquez, Yalbi Balderas, Joselyn Chávez, Erick Cuevas |
| 15:00-17:00 | Proyecto colaborativo. Parte II | Mirna Vázquez, Yalbi Balderas, Joselyn Chávez, Erick Cuevas |

### Viernes 05 de agosto

| Horario     | Tema                             | Instructor                                                  |
|-------------|----------------------------------|-------------------------------------------------------------|
| 9:00-11:00  | Proyecto colaborativo Parte III  | Mirna Vázquez, Yalbi Balderas, Joselyn Chávez, Erick Cuevas |
| 11:30-13:30 | Presentación de proyectos        | Mirna Vázquez, Yalbi Balderas, Joselyn Chávez, Erick Cuevas |
| 13:30-14:00 | Clausura                         | Mirna Vázquez, Yalbi Balderas, Joselyn Chávez, Erick Cuevas |

## Patrocinadores

Agradecemos a nuestros patrocinadores:



## Licencia

Este material posee una licencia tipo Creative Commons Attribution-ShareAlike 4.0 International License. 

Para conocer más sobre esta licencia, visite http://creativecommons.org/licenses/by-sa/4.0/

